### ISSUE TITLE
Suggested Grammar Fixes for Landing Page

### ISSUE THREAD

**Issue by DeerTears** [OpMonTeam/OpMon-Website#3]
I'd love to edit this website's text and make a pull request, but I don't know where you guys keep it in the repository. (I don't know anything about web development outside of basic HTML ;;) So here's some suggestions I have about the text on your project's homepage.

1. The description of the game at the top:
Go for an adventure... --> *Go on an adventure...*

2. The text on the red "donate" banner next to your names:
We need help, and even if you have not any knowledge in programmation, you can help us anyway by telling us the bugs you have found, or by proposing us enhancements! [Voir sur Github]
-->
*We need your help, no prior coding knowledge required! Help us find bugs or suggest new ideas! [View on Github]*

3. The descriptions under your names and avatars:
Cyrielle: Foundation and Programming, Navet56: Co-Foundation, Game-Design and Graphic Design --> *Cyrielle: Founder and Programmer , Navet56: Co-Founder, Game Designer and Graphic Designer*

Sidenote: While I think it's correct to say "I am responsible for the programming" shortened credits usually show roles instead of outcomes. Things like "Lead Artist" or "Editor In-Chief" instead of "Art" or "Editing"

That's all I've found for now, I hope this helps!

**Comment by milkyroute** [comment]
Oh, thank you ! I'll do it as soon as I can. Meanwhile, to answer your question, the text is in the js/ folder, in index.js and download.js (Which are the .js files associated with the .html files).

**Comment by milkyroute** [comment]
Done !
