### ISSUE TITLE
OpMon website is offline

### ISSUE THREAD

**Issue by ghost** [OpMonTeam/OpMon-Website#8]
Hello OpMon Team, contacting you is that I noticed that your website is offline and can only be accessed through the Wayback Machine archive. which the last file of its website is from [February 2](https://web.archive.org/web/20230208051206/https://opmon-game.ga/) of this same year.

If they no longer have the domain or their own server, I would recommend that you use [GitHub Pages](https://pages.github.com/) to host your website.

Greetings.

**Comment by milkyroute** [comment]
Thanks for reporting it! Sorry it took so long for me to respond. We actually use GitHub Pages, it’s just the domain name configuration that was outdated. It should be now fixed!
